FORMAT: 1A
HOST: http://private-a04ff1-elaura04.apiary-mock.com

# BTC Wallet

BTC Wallet is a simple API that "simulates" a platform that allow users to
register, create own BTC wallets and transfer BTC to other wallets inside it.
Platform makes 1.5% profit from the transactions between users. 
The API accepts JSON-encoded request bodies, and returns JSON-encoded responses,
and uses standard HTTP response codes and verbs.


# Important Notes

- At the moment the API is under development, so minimal endpoints are provided


# Authentication

The API uses a simple token-based HTTP Authentication scheme. To obtain a valid token,
first you must create a user. The endpoint to create users is ```/api/v1/users``` and
accepts POST requests. The endpoint returns the token that is required to authenticate
all other requests for this user.

# Versioning

API version must be specify as part of the URL path. Actual version is v1. All API
calls must start with the api version (eg. api/v1/users)

# Errors

The API uses conventional HTTP response codes to indicate the success or
failure of a request.

In general:
- 2xx codes indicate success.
- 4xx codes indicate an error that failed given the information provided. 
- 5xx codes indicate an error with the server.

**Error object attributes**

- status_code *(string)*: Standard HTTP Status Code
- error_message *(string)*: Description of the error



# Group Users Resource
This section groups users operations. At the moment just user creation
is allowed, to get a valid token.

#### Endoints
- **POST** /users

**User object attributes**

- username *(string)*
- password *(string)*:

## Users Collection [/users]

### Create a new user [POST]
Returns a token that will authenticate all other requests for this user.

+ Response 201 (application/json)

        {
            "token": "9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b"
        }



# Group Wallets Resource
This section groups wallet operations.

#### Endoints
- **POST** /wallets
- **GET**  /wallets/{address}

**Wallet object attributes**
- address *(string)*: Unique wallet identification
- alias *(string)*: Optional alternative wallet's name/id
- balance *(balance object)*: Wallet's current balance  

**Balance object attributes**
- btc *(string)*: Wallet's balance in bitcoins (readonly)
- usd *(string)*: Wallet's balance in usd (readonly)


## Wallets Collection [/wallets]

### Create a new wallet [POST]

Creates BTC wallet for the authenticated user. 1 BTC  is automatically granted
to the new wallet upon creation. User may register up to 10 wallets.
Returns wallet address and current balance in BTC and USD.

+ Request

    + Headers
    
            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b

+ Response 201 (application/json)

        {

            "address": "5073d9f2-f644-4281-8be2-a179fa790a19",
            "alias": "5073d9f2-f644-4281-8be2-a179fa790a19",
            "balance": {
                "btc": "1.00000000",
                "usd": "11661.17"
            }
        }
            

### List all wallets [GET]

Returns all wallets address availables for the authenticated user.

+ Request

    + Headers
    
            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b

+ Response 200 (application/json)

        [
            {
                "address": "5073d9f2-f644-4281-8be2-a179fa790a19",
            },
            {
                "address": "90baa934-6a87-4fd1-8a60-3f646b37a815",
            }
        ]

## Wallet Item [/wallets/{address}]

+ Parameters
    + address: `90baa934-6a87-4fd1-8a60-3f646b37a815` (string) - A valid wallet address own by authenticated the user
    

### Get wallet information [GET]

Returns wallet address and current balance in BTC and USD.

+ Request

    + Headers
    
            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b

+ Response 200 (application/json)

        {
            "address": "90baa934-6a87-4fd1-8a60-3f646b37a815",
            "alias": "90baa934-6a87-4fd1-8a60-3f646b37a815",
            "balance": {
                "btc": "1.00000000",
                "usd": "11739.46"
            }
        }


# Group Transactions Resource
This section groups all transactions operations. Transactions allows users 
to transfer bitcoins from one wallet to another wallet.

#### Endoints
- **POST** /transactions
- **GET**  /transactions
- **GET**  /wallets/{address}/transactions


**Transaction object attributes**

- wallet_from *(string)*: Wallet address origin
- wallet_to *(string)*: Wallet address destination
- transaction_type *(string)*: Type of transaction (See below allowed values)
- amount *(string, number )*: Amount of bitcoins to be transfer
- extra *(string)*: Optional text description 
- details *(string)* : Text autogenerated to describe transaction (readonly)

_Transaction valid types are:  sent_internal / sent_external_

## Transactions Collection [/transactions]

### Create a new transaction [POST]

Makes a transaction from one wallet to another inside the platform.
Transaction is free if transferred to own wallet.
Transaction costs 1.5% of the transferred amount (profit of the platform)
if transferred to a wallet of another user.
This profit is reflected as another transaction between the user who
transfers bitcoins and the platform


+ Request

    + Headers
    
            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b
            
    + Body
    
            {
                "transaction_type": "sent_internal",
                "wallet_from": "90baa934-6a87-4fd1-8a60-3f646b37a815",
                "wallet_to": "5073d9f2-f644-4281-8be2-a179fa790a19",
                "amount": "0.50000000",
                "extra": "Extra",
            }

+ Response 201 (application/json)

           {
                "transaction_type": "sent_internal",
                "wallet_from": "90baa934-6a87-4fd1-8a60-3f646b37a815",
                "wallet_to": "5073d9f2-f644-4281-8be2-a179fa790a19",
                "amount": "0.50000000",
                "details": "Transfers 0.50000000 bitcoins from 90baa934-6a87-4fd1-8a60-3f646b37a815 wallet to 5073d9f2-f644-4281-8be2-a179fa790a19 wallet.",
                "extra": "Extra",
                "created_at": "2020-08-30T13:21:19.272289Z"
            }
           
        
### List transactions [GET]

Returns user authenticated transactions

+ Request

    + Headers
    
            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b

+ Response 200 (application/json)

        [
            {
                "transaction_type": "sent_internal",
                "wallet_from": "90baa934-6a87-4fd1-8a60-3f646b37a815",
                "wallet_to": "5073d9f2-f644-4281-8be2-a179fa790a19",
                "amount": "0.50000000",
                "details": "Transfers 0.50000000 bitcoins from 90baa934-6a87-4fd1-8a60-3f646b37a815 wallet to 5073d9f2-f644-4281-8be2-a179fa790a19 wallet.",
                "extra": "Extra",
                "created_at": "2020-08-30T13:21:19.272289Z"
            },
            {
                "transaction_type": "platform",
                "wallet_from": "cb9729d0-1348-4661-9b50-dcde518068d1",
                "wallet_to": "90baa934-6a87-4fd1-8a60-3f646b37a815",
                "amount": "1.00000000",
                "details": "Platform grants 1 BTC after wallet creation.",
                "extra": "",
                "created_at": "2020-08-30T12:53:08.678294Z"
            },
            {
                "transaction_type": "platform",
                "wallet_from": "cb9729d0-1348-4661-9b50-dcde518068d1",
                "wallet_to": "5073d9f2-f644-4281-8be2-a179fa790a19",
                "amount": "1.00000000",
                "details": "Platform grants 1 BTC after wallet creation.",
                "extra": "",
                "created_at": "2020-08-30T12:38:46.421715Z"
            }
        ]
        
## Wallet's transactions Collection [/wallets/{address}/transactions]

+ Parameters
    + address: `90baa934-6a87-4fd1-8a60-3f646b37a815` (string) - A valid wallet address own by authenticated the user

### List wallet's transactions [GET]

Returns transactions related to a specific wallet

+ Request

    + Headers
    
            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b

+ Response 200 (application/json)

        [
            {
                "transaction_type": "sent_internal",
                "wallet_from": "90baa934-6a87-4fd1-8a60-3f646b37a815",
                "wallet_to": "5073d9f2-f644-4281-8be2-a179fa790a19",
                "amount": "0.50000000",
                "details": "Transfers 0.50000000 bitcoins from 90baa934-6a87-4fd1-8a60-3f646b37a815 wallet to 5073d9f2-f644-4281-8be2-a179fa790a19 wallet.",
                "extra": "Extra",
                "created_at": "2020-08-30T13:21:19.272289Z"
            },
            {
                "transaction_type": "platform",
                "wallet_from": "cb9729d0-1348-4661-9b50-dcde518068d1",
                "wallet_to": "90baa934-6a87-4fd1-8a60-3f646b37a815",
                "amount": "1.00000000",
                "details": "Platform grants 1 BTC after wallet creation.",
                "extra": "",
                "created_at": "2020-08-30T12:53:08.678294Z"
            },
            {
                "transaction_type": "platform",
                "wallet_from": "cb9729d0-1348-4661-9b50-dcde518068d1",
                "wallet_to": "5073d9f2-f644-4281-8be2-a179fa790a19",
                "amount": "1.00000000",
                "details": "Platform grants 1 BTC after wallet creation.",
                "extra": "",
                "created_at": "2020-08-30T12:38:46.421715Z"
            }
        ]
        

# Group Statistics Resource
This section groups additional endpoint for administrator.

#### Endoints
- **GET**  /statistics

## Statistics Collection [/statistics]

### List statistics [GET]

Returns the total number of transactions and platform profit. 
Authenticated with hardcoded token.

+ Request

    + Headers
    
            Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b

+ Response 200 (application/json)
    
        {
            "profit": "40.00500000",
            "transactions": 107
        }
