# Generated by Django 2.2.15 on 2020-08-27 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.Wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='alias',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
