# Generated by Django 2.2.15 on 2020-08-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200828_1134'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='unique_address',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('sent_external', 'sent_external'), ('sent_internal', 'sent_internal'), ('received_external', 'received_external'), ('received_external', 'received_external'), ('platform', 'platform')], max_length=20),
        ),
    ]
