# Generated by Django 2.2.15 on 2020-08-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200828_1612'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('address', 'user'), name='unique_useraddress'),
        ),
    ]
