# Generated by Django 2.2.15 on 2020-08-29 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200828_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('sent_external', 'sent_external'), ('sent_internal', 'sent_internal'), ('received_external', 'received_external'), ('received_external', 'received_external'), ('platform', 'platform')], max_length=20),
        ),
    ]
