# Generated by Django 2.2.15 on 2020-08-29 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200829_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transfer_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_credits', to='api.Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_debits', to='api.Wallet'),
        ),
    ]
