# Generated by Django 2.2.15 on 2020-08-29 21:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200829_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='wallet_from',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet_to',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
