# Generated by Django 2.2.15 on 2020-08-29 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200829_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_credits', to='api.Wallet', to_field='address'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_debits', to='api.Wallet', to_field='address'),
        ),
    ]
