# Generated by Django 2.2.15 on 2020-08-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200829_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('sent_external', 'sent_external'), ('sent_internal', 'sent_internal'), ('platform', 'platform')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_credits', to='api.Wallet', to_field='address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_debits', to='api.Wallet', to_field='address'),
        ),
    ]
