# Generated by Django 2.2.15 on 2020-08-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200830_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('transactions', models.IntegerField()),
                ('profit', models.DecimalField(decimal_places=8, max_digits=16)),
            ],
        ),
    ]
