# Generated by Django 2.2.15 on 2020-08-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='profit',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='transactions',
            field=models.IntegerField(default=0),
        ),
    ]
