# Generated by Django 2.2.15 on 2020-08-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200830_1357'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='unique_useraddress',
        ),
        migrations.AddField(
            model_name='transaction',
            name='extra',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('sent_external', 'sent_external'), ('sent_internal', 'sent_internal'), ('platform', 'platform'), ('platform_profit', 'platform_profit')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'alias'), name='unique_user_alias'),
        ),
    ]
